### ISSUE TITLE
No longer works on Travis for python 3.3

### ISSUE THREAD

**Issue by gappleto97** [MacPython/terryfy#7] opened 2016-10-05 03:16 UTC
https://travis-ci.org/gappleto97/p2p-project/jobs/165129936

**Comment by matthew-brett** [comment] 2016-10-05 07:33
Yes, sorry, there appears to be a bug in travis-ci's new OSX image with xcode 7.3 - see : 

https://github.com/python-pillow/pillow-wheels/issues/45

Try adding

```
osx_image: xcode6.4
```

in the global env section of your `.travis.yml` file.

**Comment by gappleto97** [comment] 2016-10-08 22:50
Using xcode 6.4 make the `cryptography` package fail on python 3.3

I've tried every build newer than that, and either my SSL tests are consistently fail, or python 3.3 won't install. Should we raise this to Travis?

**Comment by matthew-brett** [comment] 2016-10-08 23:02
Hum - that's strange.   Can you see, from the travis logs, what image you last used that worked correctly?

**Comment by gappleto97** [comment] 2016-10-08 23:21
Worked on [build 352](https://travis-ci.org/gappleto97/p2p-project/builds/164792656) using the default.

Failed on [build 353](https://travis-ci.org/gappleto97/p2p-project/builds/165077884) using the default.

Looks like those images were, respectively:

* travis-ci-osx10.9-xcode6.1-1472151920
* travis-ci-osx10.11-xcode7.3-1475610688

When I tried their xcode6.1 image on [build 371](https://travis-ci.org/gappleto97/p2p-project/builds/166124978), it selects the image above, and that seemed to work correctly. But when I tried xcode6.4 (the lowest non-beta xcode) in [build 365](https://travis-ci.org/gappleto97/p2p-project/builds/166116849) the cryptography module failed.

I then tried a build using xcode [6.2](https://travis-ci.org/gappleto97/p2p-project/builds/166125301) and [6.3](https://travis-ci.org/gappleto97/p2p-project/builds/166125326). Neither of these explicitly say that they're the correct xcode, but they seem to have different images from the other ones, so I assume they do. Either way, 6.3 didn't work.

Given this, I'm not sure if this is a bug to raise for the cryptography team, or the Travis team. Either way, I'm also experiencing the shell_session_update in https://github.com/travis-ci/travis-ci/issues/6522

**Comment by matthew-brett** [comment] 2016-10-11 17:40
I see the same as you for the xcode 6.1 and 7.3 image - with errors installing Python 3.3 on 7.3, tests passing on 6.1:

* 7.3:  https://travis-ci.org/MacPython/cython-wheels/jobs/166612119
* 6.1:  https://travis-ci.org/MacPython/cython-wheels/jobs/166813775

6.2 failed for me.   I believe the problem is that the older Python 3.3 ``.mpkg`` format installer does not work in the later OSX version, but I'm guessing.

**Comment by gappleto97** [comment] 2016-10-11 18:25
So does this mean the error is something y'all can fix? Or do we need to elevate this to some other team?

**Comment by matthew-brett** [comment] 2016-10-11 19:03
I believe that the Python 3.3 installer cannot work on OSX 10.11.  Certainly it does not work on my local machine running 10.11.   

So, unless someone can think of a way round this, the only choice for Python 3.3 is to go back to an OSX 10.9 image like xcode 6.1.

**Comment by andrewferrier** [comment] 2016-10-22 09:29
FYI - I appear to be having a similar problem. For example, this build failed on Mac with the same error message: https://travis-ci.org/andrewferrier/cromer/builds/168606135. I tried another build with `osx_image` set to `xcode6.4` and it still failed (https://travis-ci.org/andrewferrier/cromer/builds/169707129 - `xcode6.4`). Regressing this further to `xcode6.1` seems to revert back to OSX10.11 - perhaps travis-ci have removed support for XCode 6.1?

Thanks for your work on terryfy!

**Comment by andrewferrier** [comment] 2016-11-20 16:20
This appears to have now fixed itself.

**Closed** 2017-02-12 22:43 UTC
